### ISSUE TITLE
No info loading

### ISSUE THREAD

**Issue by dustying** [vdesabou/alfred-nike-plus#1]
I can see all the menu choices with my info, but selecting any of them just "quits" the workflow and gives me my default search results.

Starting debug for 'Nike Plus 1.1.3'

[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item arg="" valid="no"><arg></arg><title>TOTAL: 🏃 83 ● 🏁 340 km ● 〽️ 05:24 min/km</title><subtitle>🕐 31 hours ● Avg 🏁 4.1km ● Avg ⛽️ 908  ● Next 🔰 (blue): 660km</subtitle><icon>./images/green.png</icon><text type="copy">My #nikeplus stats: TOTAL: 🏃 83 ● 🏁 340 km ● 〽️ 05:24 min/km&#13;(collected by http://www.packal.org/workflow/nike-plus)</text><text type="largetype">My #nikeplus stats: TOTAL: 🏃 83 ● 🏁 340 km ● 〽️ 05:24 min/km&#13;(collected by http://www.packal.org/workflow/nike-plus)</text></item><item arg="" valid="no"><arg></arg><title>Road: 192 km ● Beach: 0 km ● Trendmill: 0 km ● Trail: 21 km</title><subtitle>Morning: 22 % ● Afternoon: 14 % ● Evening: 63 % ● Night: 1 %</subtitle><icon>./images/road.png</icon><text type="copy">My #nikeplus terrain stats: Road: 192 km ● Beach: 0 km ● Trendmill: 0 km ● Trail: 21 km&#13;(collected by http://www.packal.org/workflow/nike-plus)</text><text type="largetype">My #nikeplus terrain stats: Road: 192 km ● Beach: 0 km ● Trendmill: 0 km ● Trail: 21 km&#13;(collected by http://www.packal.org/workflow/nike-plus)</text></item><item arg="a:2:{i:0;s:0:&quot;&quot;;i:1;s:53:&quot;https://secure-nikeplus.nike.com/plus/profile/DustinG&quot;;}" valid="yes"><arg>a:2:{i:0;s:0:"";i:1;s:53:"https://secure-nikeplus.nike.com/plus/profile/DustinG";}</arg><title>1K: 03:40 ● 5K: 20:56 ● 10K: 00:00 ● Half-Marathon: 00:00 ● Marathon: 00:00</title><subtitle>Best 🏁 8.88 km ● 🕐 47:05 ● ⚡️ 670</subtitle><icon>./images/trophee.png</icon><text></text></item><item arg="" valid="no" autocomplete="Year▹2015▹07▹"><arg></arg><title>Browse your 🏃 for July</title><subtitle>Browse current month</subtitle><icon>./images/07.png</icon><text></text></item><item arg="" valid="no" autocomplete="Year▹"><arg></arg><title>Browse all 🏃 by year</title><subtitle>Browse by year and then by month</subtitle><icon>./images/2015.png</icon><text></text></item><item arg="" valid="no" autocomplete="All▹"><arg></arg><title>Browse all your 🏃</title><subtitle>Display all your runs</subtitle><icon>./images/track.png</icon><text></text></item><item arg="" valid="no" autocomplete="Shoes▹"><arg></arg><title>Get your shoes stats</title><subtitle>Browse all your shoes</subtitle><icon>./images/shoes.png</icon><text></text></item><item arg="" valid="no" autocomplete="Settings▹"><arg></arg><title>Go to settings</title><subtitle>Units=&lt;km&gt; User=&lt;DustinG&gt;</subtitle><icon>./images/credentials.png</icon><text></text></item></items>

**Comment by vdesabou** [comment]
Hi,

The output is truncated , can you use syntax highlighting as described https://guides.github.com/features/mastering-markdown/

Or send output by email (the one on my github profile)
Also, can you make sure to have the output when you have the issue (when you browse into sub-menu)?

**Comment by vdesabou** [comment]
any update?

**Comment by dustying** [comment]
I can't figure out how to get an output when I have the issue. Nothing happens. Sorry, I'm very familiar with this process.

**Comment by vdesabou** [comment]
here is a gif of what I expect: https://dl.dropboxusercontent.com/s/xub3v2loewf0ov0/2F18CA2C-B1F2-45B4-AFA6-D402FCB4B1DF-14648-00001BD1E170B197.gif?dl=0

The idea is to copy and paste in an email the output so that I can have a look

**Comment by dustying** [comment]
I can do gifs ;)

http://g.recordit.co/BjdMg5i9gA.gif http://g.recordit.co/BjdMg5i9gA.gif

Here's the output, I think it's the same.
Starting debug for 'Nike Plus 1.1.3'

[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0" encoding="UTF-8"?>
<items><item arg="" valid="no"><arg></arg><title>TOTAL: 🏃 85 ● 🏁 345 km ● 〽️ 05:24 min/km</title><subtitle>🕐 31 hours ● Avg 🏁 4.1km ● Avg ⛽️ 903  ● Next 🔰 (blue): 655km</subtitle><icon>./images/green.png</icon><text type="copy">My #nikeplus stats: TOTAL: 🏃 85 ● 🏁 345 km ● 〽️ 05:24 min/km&#13;(collected by http://www.packal.org/workflow/nike-plus)</text><text type="largetype">My #nikeplus stats: TOTAL: 🏃 85 ● 🏁 345 km ● 〽️ 05:24 min/km&#13;(collected by http://www.packal.org/workflow/nike-plus)</text></item><item arg="" valid="no"><arg></arg><title>Road: 198 km ● Beach: 0 km ● Trendmill: 0 km ● Trail: 21 km</title><subtitle>Morning: 21 % ● Afternoon: 14 % ● Evening: 64 % ● Night: 1 %</subtitle><icon>./images/road.png</icon><text type="copy">My #nikeplus terrain stats: Road: 198 km ● Beach: 0 km ● Trendmill: 0 km ● Trail: 21 km&#13;(collected by http://www.packal.org/workflow/nike-plus)</text><text type="largetype">My #nikeplus terrain stats: Road: 198 km ● Beach: 0 km ● Trendmill: 0 km ● Trail: 21 km&#13;(collected by http://www.packal.org/workflow/nike-plus)</text></item><item arg="a:2:{i:0;s:0:&quot;&quot;;i:1;s:53:&quot;https://secure-nikeplus.nike.com/plus/profile/DustinG&quot;;}" valid="yes"><arg>a:2:{i:0;s:0:"";i:1;s:53:"https://secure-nikeplus.nike.com/plus/profile/DustinG";}</arg><title>1K: 03:40 ● 5K: 20:56 ● 10K: 00:00 ● Half-Marathon: 00:00 ● Marathon: 00:00</title><subtitle>Best 🏁 8.88 km ● 🕐 47:05 ● ⚡️ 670</subtitle><icon>./images/trophee.png</icon><text></text></item><item arg="" valid="no" autocomplete="Year▹2015▹07▹"><arg></arg><title>Browse your 🏃 for July</title><subtitle>Browse current month</subtitle><icon>./images/07.png</icon><text></text></item><item arg="" valid="no" autocomplete="Year▹"><arg></arg><title>Browse all 🏃 by year</title><subtitle>Browse by year and then by month</subtitle><icon>./images/2015.png</icon><text></text></item><item arg="" valid="no" autocomplete="All▹"><arg></arg><title>Browse all your 🏃</title><subtitle>Display all your runs</subtitle><icon>./images/track.png</icon><text></text></item><item arg="" valid="no" autocomplete="Shoes▹"><arg></arg><title>Get your shoes stats</title><subtitle>Browse all your shoes</subtitle><icon>./images/shoes.png</icon><text></text></item><item arg="" valid="no" autocomplete="Settings▹"><arg></arg><title>Go to settings</title><subtitle>Units=&lt;km&gt; User=&lt;DustinG&gt;</subtitle><icon>./images/credentials.png</icon><text></text></item></items>

**Comment by vdesabou** [comment]
Ok I've reproduced the problem. It's because I use the workflow always with an hotkey, that's why I did not notice the problem before.

Can you try this version: https://infinit.io/_/gQanMbe

**Comment by dustying** [comment]
Wow, thanks a ton! Works like a charm!

**Comment by vdesabou** [comment]
Great ! Enjoy then :smile:
